### ISSUE TITLE
Does not work :(

### ISSUE THREAD

**Issue by danielbayerlein** [professant/sublime-galen#1]
I'm looking for a syntax highlighting for [Galen](http://galenframework.com). Unfortunately sublime-galen no longer works.

I use the following versions: 
* Sublime Text 3, Build 3103
* Galen 2.2.5

Any idea why it does not work anymore?

<img width="882" alt="bildschirmfoto 2016-04-23 um 09 06 31" src="https://cloud.githubusercontent.com/assets/457834/14759906/bdb71c2c-0933-11e6-9169-f1dba610536a.png">

/cc @erquhart

**Comment by erquhart** [comment]
Sorry mate, no clue. Haven't looked at Galen in quite some time, but I believe their syntax has moved on quite a bit since this was created.

**Comment by danielbayerlein** [comment]
Thanks for the feedback. I fork the grammar for the atom editor and fix the issues.
